### ISSUE TITLE
Use witx for autogenerating (most of) wasi_unstable::raw module

### ISSUE THREAD

**Issue by kubkon** [bytecodealliance/wasi#13]
I'm not overly familiar with [witx] yet, but (if possible) it would be beneficial to autogenerate most of `wasi_unstable::raw` module from the spec using [witx] rather than filling in the values manually. I was thinking of actually doing something similar to what's been done in CraneStation/wasi-common#152. This way, we'd avoid further errors like #12 in the future.

[witx]: https://github.com/WebAssembly/WASI/tree/master/tools/witx

**Comment by kubkon** [comment]
cc @sunfishcode

**Comment by alexcrichton** [comment]
Done now!

(as of https://github.com/bytecodealliance/wasi/pull/16)
