### ISSUE TITLE
Changing crate idioms

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasi#20]
The WASI spec has a new revision now. The old `wasi_unstable` module is now located in [a `snapshot_0`](https://github.com/WebAssembly/WASI/tree/master/phases/old/snapshot_0) directory while the now-current `wasi_snapshot_preview1` is located [in the `phases/snapshot` directory](https://github.com/WebAssembly/WASI/tree/master/phases/snapshot/witx). As a result, it's time to update this crate I think!

I wanted to take this time though to perhaps think a bit more about the crate to see if we want to change some idioms? A list of what I'm thinking is:

* Remove the `wasi_unstable` crate module. Instead the `wasi` crate would have all the high-level bindings/types in the root of the module, where a `raw` submodule would be the auto-generated raw bindings from the `*.witx` files.
* Attempt to auto-generate most of the crate root high-level bindings, such as managing slices, strings, etc, where possible. This way if interfaces change over time we can just keep running the auto-generator.
* Add the wasi snapshot name to the crate version number, similar to the way the [`openssl-src` crate works](https://crates.io/crates/openssl-src). This way the version number on crates.io can show, at a glance, what wasi version is in use and what wasi bindings the module contains.
* Remove the `__wasi` prefix from all APIs, we've got a module system in Rust so no need to follow C in this regard!

That's what I've got on my mind as-is, do others have thoughts on this? I don't mind doing some of the legwork to try to get this done myself.

**Comment by sunfishcode** [comment]
>  Remove the wasi_unstable crate module. Instead the wasi crate would have all the high-level bindings/types in the root of the module, where a raw submodule would be the auto-generated raw bindings from the *.witx files.

This makes sense. My original idea was that the wasi crate could host multiple versions of the ABI, with both `wasi_unstable` and `wasi_snapshot_preview1` existing side by side. However, I now think you're right, and we can simplify things now.

> Attempt to auto-generate most of the crate root high-level bindings, such as managing slices, strings, etc, where possible. This way if interfaces change over time we can just keep running the auto-generator.

Yes, I share this goal :-).

> Add the wasi snapshot name to the crate version number, similar to the way the openssl-src crate works. This way the version number on crates.io can show, at a glance, what wasi version is in use and what wasi bindings the module contains.

That makes sense along with your first point.

> Remove the __wasi prefix from all APIs, we've got a module system in Rust so no need to follow C in this regard!

Yes! This is much easier now that we have a witx generator, and now that witx itself moving to less C-specific names (see https://github.com/bytecodealliance/wasi/pull/21).
