### ISSUE TITLE
Support building bindings to wasi_ephemeral_

### ISSUE THREAD

**Issue by joshtriplett** [bytecodealliance/wasi#28]
Currently, generate-raw hardcodes the generation of bindings to `wasi_snapshot_preview1`, and the generated bindings call the corresponding functions.

To aid in experimentation and WASI development, would it make sense to support generating a version of the bindings for `wasi_ephemeral_preview`? (Such a version wouldn't get published to crates.io, but could support local development.)

**Comment by alexcrichton** [comment]
This seems plausible to add as maybe a wasi-ephemeral crate that could love as a git dep most of the time?

**Comment by joshtriplett** [comment]
@alexcrichton That sounds even better, yes! I'd expect to use it as either a git dep or path dep most of the time (a path dep when working on new APIs, a git dep when using new pre-snapshot APIs).

Ideally, I'd love to see the code generation for wasi-ephemeral happen in `build.rs` so that it automatically re-runs when built as a path dep, without having to re-run the code generation manually when changing the witx file. wasi-ephemeral could have a dev-dependency on generate-raw by path for that.

I'd be happy to submit a draft pull request for that. (It won't build yet, until generate-raw becomes capable of rendering witx files that use handle types.)

**Comment by joshtriplett** [comment]
Fixed in #31
