### ISSUE TITLE
Missing stdio consts intentional?

### ISSUE THREAD

**Issue by kubkon** [bytecodealliance/wasi#36]
In the latest version of the crate (`0.9.0`), there seem to be consts representing stdio fds missing (previously these would have been `STDIN_FD`, `STDOUT_FD`, and `STDERR_FD`). Is this intentional? Is the user now expected to define these themselves?

I'm somewhat confused by this since `wasi::Fd` values `[0,1,2]` are reserved in `wasi-common` for that very purpose. The only reason of leaving them out from the `wasi` crate and having the user define them themselves is if they decide not to have certain stdio handles hooked up. Am I correct here?

**Comment by sunfishcode** [comment]
It seems like we can reasonably define these. I've now opened https://github.com/bytecodealliance/wasi/pull/38 to implemented this.
