### ISSUE TITLE
`strerror` function only generated for `Errno`

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasi#52]
`witx-bindgen` generated a function that maps WASI error codes from their `u16` representation to their documentation string. Currently this function is only generated when the type is named `errno` (see [here](https://github.com/bytecodealliance/wasi/blob/main/crates/witx-bindgen/src/lib.rs#L174-L189)). For wasi-nn, it would be nice to generate a similar `strerror` function, so we could:
 - change the logic to `name.ends_with("errno")`
 - add methods to witx-bindgen to configure which types get the `strerror` treatment.

**Comment by sunfishcode** [comment]
Would it make sense to change the logic to generate the function for *all* enums? Instead of "strerror", we could name the function something derived from the enum name.

**Comment by pchickey** [comment]
Can't we just `#[derive(Debug)]` on all enums?

**Comment by sunfishcode** [comment]
The `strerror` function uses the strings from `docs.trim()`, which is a more informative than `derive(Debug)`.

**Comment by pchickey** [comment]
oh! my bad. Maybe we should define a `trait WitxDocs { fn docs(&self) -> String }` and generate impls for that?

**Comment by sunfishcode** [comment]
Sounds good to me! It might even use `&'static str` rather than `String`.

**Comment by alexcrichton** [comment]
I think this is [more-or-less done now](https://github.com/bytecodealliance/wasi/blob/f611c93a68e3c6c0ec114141736aedf45fe77f34/src/bindings.rs#L1100-L1139) with wit-bindgen, so I'm going to close this.
