### ISSUE TITLE
Publish witx-bindgen to crates.io

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasi#53]
I am using `witx-bindgen` (previously `generate-raw`) in a similar library to this one but for wasi-nn. I manually created and tweaked the generated Rust code and can use that in my repo but at some point it would be good to generate this in CI (or at least generate in CI to check for changes). To do so, I would need for `witx-bindgen` to be published. Can we publish it?

**Comment by pchickey** [comment]
Yes, we should publish it - I will defer to @alexcrichton but if he is busy I can take care of it

**Comment by alexcrichton** [comment]
Sure thing, published!
