### ISSUE TITLE
`Into<NonZeroU16>` for `wasi::Error`

### ISSUE THREAD

**Issue by Cyborus04** [bytecodealliance/wasi#61]
In rust-random/getrandom#233 an optimization depending on `wasi::Error::raw_error` never returning 0 was added, which AFAIK is guaranteed but not as part of public API.  This PR was accepted but would rather have direct conversion to `NonZeroU16` to ensure this guarantee. Would that be possible? I looked into directly opening a PR for this but I'm not sure how that would be added

**Comment by Cyborus04** [comment]
What about a documented guarantee that none of the functions will ever return `Err(ERRNO_SUCCESS)`?

**Comment by alexcrichton** [comment]
This crate has now updated to WASI 0.2.0 and so this issue I believe is no longer applicable as the underlying APIs have chagned in the meantime. I'm going to close this because of that, but API suggestions for the currently generated APIs are definitely welcome!
