### ISSUE TITLE
Add (back) constructor for Errno

### ISSUE THREAD

**Issue by Thomasdezeeuw** [bytecodealliance/wasi#64]
Title says it all, would you consider adding back a constructor similar to `Error::from_raw_error` used to be?

Required for `getrandom` crate: https://github.com/rust-random/getrandom/blob/157d6f23dc53ea995294646c4f6301116aaa2bfa/src/error.rs#L113-L115.

**Comment by newpavlov** [comment]
Relevant comment: https://github.com/bytecodealliance/wasi/pull/59#issuecomment-1018783846

**Comment by alexcrichton** [comment]
This crate has now upgraded to WASI 0.2.0 which is much different from the previous `wasi_snapshot_preview1` module. In that sense this issue is no longer applicable as this is for a historical version of the crate at this point. Because of that I'm going to close this.
