### ISSUE TITLE
`witx-bingen` generates incorrect lifetimes

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasi#65]
In regenerating the wasi-nn bindings from a WITX file using the latest version of `witx-bingen` on `main`, I found that it generated code that would not compile. The lifetimes of several fields seemed to be incorrect--under-specified--and the bindings would no longer compile. I manually made the following changes which seem to resolve the compilation failure.

```diff
 #[repr(C)]
 #[derive(Copy, Clone, Debug)]
-pub struct Tensor {
-    pub dimensions: TensorDimensions<'_>,
+pub struct Tensor<'a> {
+    pub dimensions: TensorDimensions<'a>,
     pub type_: TensorType,
-    pub data: TensorData<'_>,
+    pub data: TensorData<'a>,
 }
 pub type GraphBuilder<'a> = &'a [u8];
-pub type GraphBuilderArray<'a> = &'a [GraphBuilder<'_>];
+pub type GraphBuilderArray<'a> = &'a [GraphBuilder<'a>];
 pub type Graph = u32;
```

Is this fixable and where could this be fixed in `witx-bindgen`?

**Comment by abrown** [comment]
cc: @pchickey?

**Comment by geekbeast** [comment]
I just hit this as well.

**Comment by pchickey** [comment]
Hi, sorry that I missed this issue last year. I am not able to spend time on this bug right now. @geekbeast if you are up for working on a fix, I will review and release it.

**Comment by geekbeast** [comment]
Will this still be an issue once preview2 ships? If so then I can take a look it. If not would make more sense to focus on getting wasi-nn moved over to that as it solves a lot of the pain involving buffers.

**Comment by pchickey** [comment]
Witx interface descriptions and bindings generation is replaced with wit tooling (wit-bindgen etc) in preview 2 & the component model. I agree it would make more sense to focus on moving proposals over to the component model at this point.

**Comment by alexcrichton** [comment]
I'm going to close this since bindings generation has moved away from witx and now lives at https://github.com/bytecodealliance/wit-bindgen
