### ISSUE TITLE
Add constants for SubscriptionU.tag

### ISSUE THREAD

**Issue by Puellaquae** [bytecodealliance/wasi#66]
Would you consider adding a struct to wrap `SubscriptionU.tag` and adding some constants?

**Comment by sunfishcode** [comment]
The work in this space is to replace the witx-based APIs with a wit-based API, where instead of a raw `union`, we can have a `variant`, which much richer support.

**Comment by alexcrichton** [comment]
WASI has changed a lot in the meantime up to 0.2, so I don't think this issue is as relevant as it once was, so I'm going to close this.
