### ISSUE TITLE
Is it safe to pass negative lengths to functions?

### ISSUE THREAD

**Issue by newpavlov** [bytecodealliance/wasi#67]
`random_get` has the following signature:
```rust
pub fn random_get(arg0: i32, arg1: i32) -> i32;
```
Meanwhile in the witx files it's defined as:
```witx
(typename $size u32)

  (@interface func (export "random_get")
    ;;; The buffer to fill with random data.
    (param $buf (@witx pointer u8))
    (param $buf_len $size)
    (result $error (expected (error $errno)))
  )
```

Assuming buffer length is casted from `usize` to `i32`, would it work correctly? Note that according to this [comment](https://github.com/rust-lang/rust/issues/101899#issuecomment-1256855113):
>none of our 3 WASM environments (Emscripten, wasi-libc, wasm32-unknown-unknown) enforce `isize::MAX` right now

Is there a reason why all arguments and return values are defined use `i32` instead of more descriptive types used in the witx files?

**Comment by sunfishcode** [comment]
In particular, it's fine to cast arbitrary `usize` to `i32` for the purpose of calling "random_get". The API here is just using the `i32` as a way to pass 32 bits of information, and not as a way to interpret it as a signed quantity.

**Comment by newpavlov** [comment]
I think it could be worth to use the more descriptive types, but the main question was answered, so I will close this issue.
