### ISSUE TITLE
Generate Wasm binaries from Rust written with the 'wasi' crate?

### ISSUE THREAD

**Issue by orangeC23** [bytecodealliance/wasi#70]
After compiling Rust code written with the `wasi` crate into WebAssembly (Wasm), can Wasm files generated this way be executed in Wasm runtimes that are not written in Rust?

**Comment by devsnek** [comment]
yes. you can learn more about webassembly here: https://developer.mozilla.org/en-US/docs/WebAssembly

**Comment by orangeC23** [comment]
Thanks!
