### ISSUE TITLE
Update published bindings to Preview 2

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/wasi#71]
Now that Preview 2 has been ratified, we should publish a checked-in version of the generated Preview 2 bindings. I'm not sure what the full range of dependencies for this are, but presumably we'll want to use `cargo-component` for this.

**Comment by alexcrichton** [comment]
Good point! I'll work on giving this a stab unless someone's already got this underway.

**Comment by sunfishcode** [comment]
This is now done, in https://github.com/bytecodealliance/wasi/pull/72, and published to crates.io as wasi 0.12.0+wasi-0.2.0.
