### ISSUE TITLE
using the `wasi` crate for the proxy world

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/wasi#79]
In [this example](https://github.com/sunfishcode/hello-wasi-http/blob/31a51d3a952dcb73a5eeee3a51e38b6227429d46/src/lib.rs#L10) the entry point for the proxy world is generated via `wit-bindgen` like so:

```rust
mod bindings;

pub use bindings::wasi::http::types::{IncomingRequest, ResponseOutparam};

struct Component;

impl bindings::exports::wasi::http::incoming_handler::Guest for Component {
    fn handle(req: IncomingRequest, res: ResponseOutparam) { ... }
}
```

The `wasi` crate does not seem to provide the equivalent of the `incoming_handler::Guest` trait here. So I don't believe there is a way to implement the world, and we have to use manual `wit-bindgen` bindings instead? Is this trait something we could generate? Even as an alias?

**Comment by alexcrichton** [comment]
Indeed #77 I believe solves this!
